const pokemon = [
    {
        id: 1,
        name: {
            english: "Bulbasaur",
            japanese: "フシギダネ",
            chinese: "妙蛙种子",
            french: "Bulbizarre",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png",
    },
    {
        id: 2,
        name: {
            english: "Ivysaur",
            japanese: "フシギソウ",
            chinese: "妙蛙草",
            french: "Herbizarre",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/2.png",
    },
    {
        id: 3,
        name: {
            english: "Venusaur",
            japanese: "フシギバナ",
            chinese: "妙蛙花",
            french: "Florizarre",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/3.png",
    },
    {
        id: 4,
        name: {
            english: "Charmander",
            japanese: "ヒトカゲ",
            chinese: "小火龙",
            french: "Salamèche",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/4.png",
    },
    {
        id: 5,
        name: {
            english: "Charmeleon",
            japanese: "リザード",
            chinese: "火恐龙",
            french: "Reptincel",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/5.png",
    },
    {
        id: 6,
        name: {
            english: "Charizard",
            japanese: "リザードン",
            chinese: "喷火龙",
            french: "Dracaufeu",
        },
        type: ["Fire", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png",
    },
    {
        id: 7,
        name: {
            english: "Squirtle",
            japanese: "ゼニガメ",
            chinese: "杰尼龟",
            french: "Carapuce",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/7.png",
    },
    {
        id: 8,
        name: {
            english: "Wartortle",
            japanese: "カメール",
            chinese: "卡咪龟",
            french: "Carabaffe",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/8.png",
    },
    {
        id: 9,
        name: {
            english: "Blastoise",
            japanese: "カメックス",
            chinese: "水箭龟",
            french: "Tortank",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png",
    },
    {
        id: 10,
        name: {
            english: "Caterpie",
            japanese: "キャタピー",
            chinese: "绿毛虫",
            french: "Chenipan",
        },
        type: ["Bug"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/10.png",
    },
    {
        id: 11,
        name: {
            english: "Metapod",
            japanese: "トランセル",
            chinese: "铁甲蛹",
            french: "Chrysacier",
        },
        type: ["Bug"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/11.png",
    },
    {
        id: 12,
        name: {
            english: "Butterfree",
            japanese: "バタフリー",
            chinese: "巴大蝶",
            french: "Papilusion",
        },
        type: ["Bug", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/12.png",
    },
    {
        id: 13,
        name: {
            english: "Weedle",
            japanese: "ビードル",
            chinese: "独角虫",
            french: "Aspicot",
        },
        type: ["Bug", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/13.png",
    },
    {
        id: 14,
        name: {
            english: "Kakuna",
            japanese: "コクーン",
            chinese: "铁壳蛹",
            french: "Coconfort",
        },
        type: ["Bug", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/14.png",
    },
    {
        id: 15,
        name: {
            english: "Beedrill",
            japanese: "スピアー",
            chinese: "大针蜂",
            french: "Dardargnan",
        },
        type: ["Bug", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/15.png",
    },
    {
        id: 16,
        name: {
            english: "Pidgey",
            japanese: "ポッポ",
            chinese: "波波",
            french: "Roucool",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/16.png",
    },
    {
        id: 17,
        name: {
            english: "Pidgeotto",
            japanese: "ピジョン",
            chinese: "比比鸟",
            french: "Roucoups",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/17.png",
    },
    {
        id: 18,
        name: {
            english: "Pidgeot",
            japanese: "ピジョット",
            chinese: "大比鸟",
            french: "Roucarnage",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/18.png",
    },
    {
        id: 19,
        name: {
            english: "Rattata",
            japanese: "コラッタ",
            chinese: "小拉达",
            french: "Rattata",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/19.png",
    },
    {
        id: 20,
        name: {
            english: "Raticate",
            japanese: "ラッタ",
            chinese: "拉达",
            french: "Rattatac",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/20.png",
    },
    {
        id: 21,
        name: {
            english: "Spearow",
            japanese: "オニスズメ",
            chinese: "烈雀",
            french: "Piafabec",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png",
    },
    {
        id: 22,
        name: {
            english: "Fearow",
            japanese: "オニドリル",
            chinese: "大嘴雀",
            french: "Rapasdepic",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/22.png",
    },
    {
        id: 23,
        name: {
            english: "Ekans",
            japanese: "アーボ",
            chinese: "阿柏蛇",
            french: "Abo",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/23.png",
    },
    {
        id: 24,
        name: {
            english: "Arbok",
            japanese: "アーボック",
            chinese: "阿柏怪",
            french: "Arbok",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/24.png",
    },
    {
        id: 25,
        name: {
            english: "Pikachu",
            japanese: "ピカチュウ",
            chinese: "皮卡丘",
            french: "Pikachu",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png",
    },
    {
        id: 26,
        name: {
            english: "Raichu",
            japanese: "ライチュウ",
            chinese: "雷丘",
            french: "Raichu",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/26.png",
    },
    {
        id: 27,
        name: {
            english: "Sandshrew",
            japanese: "サンド",
            chinese: "穿山鼠",
            french: "Sabelette",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/27.png",
    },
    {
        id: 28,
        name: {
            english: "Sandslash",
            japanese: "サンドパン",
            chinese: "穿山王",
            french: "Sablaireau",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/28.png",
    },
    {
        id: 29,
        name: {
            english: "Nidoran♀",
            japanese: "ニドラン♀",
            chinese: "尼多兰",
            french: "Nidoran♀",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/29.png",
    },
    {
        id: 30,
        name: {
            english: "Nidorina",
            japanese: "ニドリーナ",
            chinese: "尼多娜",
            french: "Nidorina",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/30.png",
    },
    {
        id: 31,
        name: {
            english: "Nidoqueen",
            japanese: "ニドクイン",
            chinese: "尼多后",
            french: "Nidoqueen",
        },
        type: ["Poison", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/31.png",
    },
    {
        id: 32,
        name: {
            english: "Nidoran♂",
            japanese: "ニドラン♂",
            chinese: "尼多朗",
            french: "Nidoran♂",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/32.png",
    },
    {
        id: 33,
        name: {
            english: "Nidorino",
            japanese: "ニドリーノ",
            chinese: "尼多力诺",
            french: "Nidorino",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/33.png",
    },
    {
        id: 34,
        name: {
            english: "Nidoking",
            japanese: "ニドキング",
            chinese: "尼多王",
            french: "Nidoking",
        },
        type: ["Poison", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/34.png",
    },
    {
        id: 35,
        name: {
            english: "Clefairy",
            japanese: "ピッピ",
            chinese: "皮皮",
            french: "Mélofée",
        },
        type: ["Fairy"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/35.png",
    },
    {
        id: 36,
        name: {
            english: "Clefable",
            japanese: "ピクシー",
            chinese: "皮可西",
            french: "Mélodelfe",
        },
        type: ["Fairy"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/36.png",
    },
    {
        id: 37,
        name: {
            english: "Vulpix",
            japanese: "ロコン",
            chinese: "六尾",
            french: "Goupix",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/37.png",
    },
    {
        id: 38,
        name: {
            english: "Ninetales",
            japanese: "キュウコン",
            chinese: "九尾",
            french: "Feunard",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/38.png",
    },
    {
        id: 39,
        name: {
            english: "Jigglypuff",
            japanese: "プリン",
            chinese: "胖丁",
            french: "Rondoudou",
        },
        type: ["Normal", "Fairy"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/39.png",
    },
    {
        id: 40,
        name: {
            english: "Wigglytuff",
            japanese: "プクリン",
            chinese: "胖可丁",
            french: "Grodoudou",
        },
        type: ["Normal", "Fairy"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/40.png",
    },
    {
        id: 41,
        name: {
            english: "Zubat",
            japanese: "ズバット",
            chinese: "超音蝠",
            french: "Nosferapti",
        },
        type: ["Poison", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/41.png",
    },
    {
        id: 42,
        name: {
            english: "Golbat",
            japanese: "ゴルバット",
            chinese: "大嘴蝠",
            french: "Nosferalto",
        },
        type: ["Poison", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/42.png",
    },
    {
        id: 43,
        name: {
            english: "Oddish",
            japanese: "ナゾノクサ",
            chinese: "走路草",
            french: "Mystherbe",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/43.png",
    },
    {
        id: 44,
        name: {
            english: "Gloom",
            japanese: "クサイハナ",
            chinese: "臭臭花",
            french: "Ortide",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/44.png",
    },
    {
        id: 45,
        name: {
            english: "Vileplume",
            japanese: "ラフレシア",
            chinese: "霸王花",
            french: "Rafflesia",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/45.png",
    },
    {
        id: 46,
        name: {
            english: "Paras",
            japanese: "パラス",
            chinese: "派拉斯",
            french: "Paras",
        },
        type: ["Bug", "Grass"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/46.png",
    },
    {
        id: 47,
        name: {
            english: "Parasect",
            japanese: "パラセクト",
            chinese: "派拉斯特",
            french: "Parasect",
        },
        type: ["Bug", "Grass"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/47.png",
    },
    {
        id: 48,
        name: {
            english: "Venonat",
            japanese: "コンパン",
            chinese: "毛球",
            french: "Mimitoss",
        },
        type: ["Bug", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/48.png",
    },
    {
        id: 49,
        name: {
            english: "Venomoth",
            japanese: "モルフォン",
            chinese: "摩鲁蛾",
            french: "Aéromite",
        },
        type: ["Bug", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/49.png",
    },
    {
        id: 50,
        name: {
            english: "Diglett",
            japanese: "ディグダ",
            chinese: "地鼠",
            french: "Taupiqueur",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/50.png",
    },
    {
        id: 51,
        name: {
            english: "Dugtrio",
            japanese: "ダグトリオ",
            chinese: "三地鼠",
            french: "Triopikeur",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/51.png",
    },
    {
        id: 52,
        name: {
            english: "Meowth",
            japanese: "ニャース",
            chinese: "喵喵",
            french: "Miaouss",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/52.png",
    },
    {
        id: 53,
        name: {
            english: "Persian",
            japanese: "ペルシアン",
            chinese: "猫老大",
            french: "Persian",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/53.png",
    },
    {
        id: 54,
        name: {
            english: "Psyduck",
            japanese: "コダック",
            chinese: "可达鸭",
            french: "Psykokwak",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/54.png",
    },
    {
        id: 55,
        name: {
            english: "Golduck",
            japanese: "ゴルダック",
            chinese: "哥达鸭",
            french: "Akwakwak",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/55.png",
    },
    {
        id: 56,
        name: {
            english: "Mankey",
            japanese: "マンキー",
            chinese: "猴怪",
            french: "Férosinge",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/56.png",
    },
    {
        id: 57,
        name: {
            english: "Primeape",
            japanese: "オコリザル",
            chinese: "火暴猴",
            french: "Colossinge",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/57.png",
    },
    {
        id: 58,
        name: {
            english: "Growlithe",
            japanese: "ガーディ",
            chinese: "卡蒂狗",
            french: "Caninos",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/58.png",
    },
    {
        id: 59,
        name: {
            english: "Arcanine",
            japanese: "ウインディ",
            chinese: "风速狗",
            french: "Arcanin",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/59.png",
    },
    {
        id: 60,
        name: {
            english: "Poliwag",
            japanese: "ニョロモ",
            chinese: "蚊香蝌蚪",
            french: "Ptitard",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/60.png",
    },
    {
        id: 61,
        name: {
            english: "Poliwhirl",
            japanese: "ニョロゾ",
            chinese: "蚊香君",
            french: "Têtarte",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/61.png",
    },
    {
        id: 62,
        name: {
            english: "Poliwrath",
            japanese: "ニョロボン",
            chinese: "蚊香泳士",
            french: "Tartard",
        },
        type: ["Water", "Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/62.png",
    },
    {
        id: 63,
        name: {
            english: "Abra",
            japanese: "ケーシィ",
            chinese: "凯西",
            french: "Abra",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/63.png",
    },
    {
        id: 64,
        name: {
            english: "Kadabra",
            japanese: "ユンゲラー",
            chinese: "勇基拉",
            french: "Kadabra",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/64.png",
    },
    {
        id: 65,
        name: {
            english: "Alakazam",
            japanese: "フーディン",
            chinese: "胡地",
            french: "Alakazam",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/65.png",
    },
    {
        id: 66,
        name: {
            english: "Machop",
            japanese: "ワンリキー",
            chinese: "腕力",
            french: "Machoc",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/66.png",
    },
    {
        id: 67,
        name: {
            english: "Machoke",
            japanese: "ゴーリキー",
            chinese: "豪力",
            french: "Machopeur",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/67.png",
    },
    {
        id: 68,
        name: {
            english: "Machamp",
            japanese: "カイリキー",
            chinese: "怪力",
            french: "Mackogneur",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/68.png",
    },
    {
        id: 69,
        name: {
            english: "Bellsprout",
            japanese: "マダツボミ",
            chinese: "喇叭芽",
            french: "Chétiflor",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/69.png",
    },
    {
        id: 70,
        name: {
            english: "Weepinbell",
            japanese: "ウツドン",
            chinese: "口呆花",
            french: "Boustiflor",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/70.png",
    },
    {
        id: 71,
        name: {
            english: "Victreebel",
            japanese: "ウツボット",
            chinese: "大食花",
            french: "Empiflor",
        },
        type: ["Grass", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/71.png",
    },
    {
        id: 72,
        name: {
            english: "Tentacool",
            japanese: "メノクラゲ",
            chinese: "玛瑙水母",
            french: "Tentacool",
        },
        type: ["Water", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/72.png",
    },
    {
        id: 73,
        name: {
            english: "Tentacruel",
            japanese: "ドククラゲ",
            chinese: "毒刺水母",
            french: "Tentacruel",
        },
        type: ["Water", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/73.png",
    },
    {
        id: 74,
        name: {
            english: "Geodude",
            japanese: "イシツブテ",
            chinese: "小拳石",
            french: "Racaillou",
        },
        type: ["Rock", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/74.png",
    },
    {
        id: 75,
        name: {
            english: "Graveler",
            japanese: "ゴローン",
            chinese: "隆隆石",
            french: "Gravalanch",
        },
        type: ["Rock", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/75.png",
    },
    {
        id: 76,
        name: {
            english: "Golem",
            japanese: "ゴローニャ",
            chinese: "隆隆岩",
            french: "Grolem",
        },
        type: ["Rock", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/76.png",
    },
    {
        id: 77,
        name: {
            english: "Ponyta",
            japanese: "ポニータ",
            chinese: "小火马",
            french: "Ponyta",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/77.png",
    },
    {
        id: 78,
        name: {
            english: "Rapidash",
            japanese: "ギャロップ",
            chinese: "烈焰马",
            french: "Galopa",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/78.png",
    },
    {
        id: 79,
        name: {
            english: "Slowpoke",
            japanese: "ヤドン",
            chinese: "呆呆兽",
            french: "Ramoloss",
        },
        type: ["Water", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/79.png",
    },
    {
        id: 80,
        name: {
            english: "Slowbro",
            japanese: "ヤドラン",
            chinese: "呆壳兽",
            french: "Flagadoss",
        },
        type: ["Water", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/80.png",
    },
    {
        id: 81,
        name: {
            english: "Magnemite",
            japanese: "コイル",
            chinese: "小磁怪",
            french: "Magnéti",
        },
        type: ["Electric", "Steel"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/81.png",
    },
    {
        id: 82,
        name: {
            english: "Magneton",
            japanese: "レアコイル",
            chinese: "三合一磁怪",
            french: "Magnéton",
        },
        type: ["Electric", "Steel"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/82.png",
    },
    {
        id: 83,
        name: {
            english: "Farfetch'd",
            japanese: "カモネギ",
            chinese: "大葱鸭",
            french: "Canarticho",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/83.png",
    },
    {
        id: 84,
        name: {
            english: "Doduo",
            japanese: "ドードー",
            chinese: "嘟嘟",
            french: "Doduo",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/84.png",
    },
    {
        id: 85,
        name: {
            english: "Dodrio",
            japanese: "ドードリオ",
            chinese: "嘟嘟利",
            french: "Dodrio",
        },
        type: ["Normal", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/85.png",
    },
    {
        id: 86,
        name: {
            english: "Seel",
            japanese: "パウワウ",
            chinese: "小海狮",
            french: "Otaria",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/86.png",
    },
    {
        id: 87,
        name: {
            english: "Dewgong",
            japanese: "ジュゴン",
            chinese: "白海狮",
            french: "Lamantine",
        },
        type: ["Water", "Ice"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/87.png",
    },
    {
        id: 88,
        name: {
            english: "Grimer",
            japanese: "ベトベター",
            chinese: "臭泥",
            french: "Tadmorv",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/88.png",
    },
    {
        id: 89,
        name: {
            english: "Muk",
            japanese: "ベトベトン",
            chinese: "臭臭泥",
            french: "Grotadmorv",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/89.png",
    },
    {
        id: 90,
        name: {
            english: "Shellder",
            japanese: "シェルダー",
            chinese: "大舌贝",
            french: "Kokiyas",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/90.png",
    },
    {
        id: 91,
        name: {
            english: "Cloyster",
            japanese: "パルシェン",
            chinese: "刺甲贝",
            french: "Crustabri",
        },
        type: ["Water", "Ice"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/91.png",
    },
    {
        id: 92,
        name: {
            english: "Gastly",
            japanese: "ゴース",
            chinese: "鬼斯",
            french: "Fantominus",
        },
        type: ["Ghost", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/92.png",
    },
    {
        id: 93,
        name: {
            english: "Haunter",
            japanese: "ゴースト",
            chinese: "鬼斯通",
            french: "Spectrum",
        },
        type: ["Ghost", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/93.png",
    },
    {
        id: 94,
        name: {
            english: "Gengar",
            japanese: "ゲンガー",
            chinese: "耿鬼",
            french: "Ectoplasma",
        },
        type: ["Ghost", "Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png",
    },
    {
        id: 95,
        name: {
            english: "Onix",
            japanese: "イワーク",
            chinese: "大岩蛇",
            french: "Onix",
        },
        type: ["Rock", "Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/95.png",
    },
    {
        id: 96,
        name: {
            english: "Drowzee",
            japanese: "スリープ",
            chinese: "催眠貘",
            french: "Soporifik",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/96.png",
    },
    {
        id: 97,
        name: {
            english: "Hypno",
            japanese: "スリーパー",
            chinese: "引梦貘人",
            french: "Hypnomade",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/97.png",
    },
    {
        id: 98,
        name: {
            english: "Krabby",
            japanese: "クラブ",
            chinese: "大钳蟹",
            french: "Krabby",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/98.png",
    },
    {
        id: 99,
        name: {
            english: "Kingler",
            japanese: "キングラー",
            chinese: "巨钳蟹",
            french: "Krabboss",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/99.png",
    },
    {
        id: 100,
        name: {
            english: "Voltorb",
            japanese: "ビリリダマ",
            chinese: "霹雳电球",
            french: "Voltorbe",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/100.png",
    },
    {
        id: 101,
        name: {
            english: "Electrode",
            japanese: "マルマイン",
            chinese: "顽皮雷弹",
            french: "Électrode",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/101.png",
    },
    {
        id: 102,
        name: {
            english: "Exeggcute",
            japanese: "タマタマ",
            chinese: "蛋蛋",
            french: "Noeunoeuf",
        },
        type: ["Grass", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/102.png",
    },
    {
        id: 103,
        name: {
            english: "Exeggutor",
            japanese: "ナッシー",
            chinese: "椰蛋树",
            french: "Noadkoko",
        },
        type: ["Grass", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/103.png",
    },
    {
        id: 104,
        name: {
            english: "Cubone",
            japanese: "カラカラ",
            chinese: "卡拉卡拉",
            french: "Osselait",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/104.png",
    },
    {
        id: 105,
        name: {
            english: "Marowak",
            japanese: "ガラガラ",
            chinese: "嘎啦嘎啦",
            french: "Ossatueur",
        },
        type: ["Ground"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/105.png",
    },
    {
        id: 106,
        name: {
            english: "Hitmonlee",
            japanese: "サワムラー",
            chinese: "飞腿郎",
            french: "Kicklee",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/106.png",
    },
    {
        id: 107,
        name: {
            english: "Hitmonchan",
            japanese: "エビワラー",
            chinese: "快拳郎",
            french: "Tygnon",
        },
        type: ["Fighting"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/107.png",
    },
    {
        id: 108,
        name: {
            english: "Lickitung",
            japanese: "ベロリンガ",
            chinese: "大舌头",
            french: "Excelangue",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/108.png",
    },
    {
        id: 109,
        name: {
            english: "Koffing",
            japanese: "ドガース",
            chinese: "瓦斯弹",
            french: "Smogo",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/109.png",
    },
    {
        id: 110,
        name: {
            english: "Weezing",
            japanese: "マタドガス",
            chinese: "双弹瓦斯",
            french: "Smogogo",
        },
        type: ["Poison"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/110.png",
    },
    {
        id: 111,
        name: {
            english: "Rhyhorn",
            japanese: "サイホーン",
            chinese: "独角犀牛",
            french: "Rhinocorne",
        },
        type: ["Ground", "Rock"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/111.png",
    },
    {
        id: 112,
        name: {
            english: "Rhydon",
            japanese: "サイドン",
            chinese: "钻角犀兽",
            french: "Rhinoféros",
        },
        type: ["Ground", "Rock"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/112.png",
    },
    {
        id: 113,
        name: {
            english: "Chansey",
            japanese: "ラッキー",
            chinese: "吉利蛋",
            french: "Leveinard",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/113.png",
    },
    {
        id: 114,
        name: {
            english: "Tangela",
            japanese: "モンジャラ",
            chinese: "蔓藤怪",
            french: "Saquedeneu",
        },
        type: ["Grass"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/114.png",
    },
    {
        id: 115,
        name: {
            english: "Kangaskhan",
            japanese: "ガルーラ",
            chinese: "袋兽",
            french: "Kangourex",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/115.png",
    },
    {
        id: 116,
        name: {
            english: "Horsea",
            japanese: "タッツー",
            chinese: "墨海马",
            french: "Hypotrempe",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/116.png",
    },
    {
        id: 117,
        name: {
            english: "Seadra",
            japanese: "シードラ",
            chinese: "海刺龙",
            french: "Hypocéan",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/117.png",
    },
    {
        id: 118,
        name: {
            english: "Goldeen",
            japanese: "トサキント",
            chinese: "角金鱼",
            french: "Poissirène",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/118.png",
    },
    {
        id: 119,
        name: {
            english: "Seaking",
            japanese: "アズマオウ",
            chinese: "金鱼王",
            french: "Poissoroy",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/119.png",
    },
    {
        id: 120,
        name: {
            english: "Staryu",
            japanese: "ヒトデマン",
            chinese: "海星星",
            french: "Stari",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/120.png",
    },
    {
        id: 121,
        name: {
            english: "Starmie",
            japanese: "スターミー",
            chinese: "宝石海星",
            french: "Staross",
        },
        type: ["Water", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/121.png",
    },
    {
        id: 122,
        name: {
            english: "Mr. Mime",
            japanese: "バリヤード",
            chinese: "魔墙人偶",
            french: "M. Mime",
        },
        type: ["Psychic", "Fairy"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/122.png",
    },
    {
        id: 123,
        name: {
            english: "Scyther",
            japanese: "ストライク",
            chinese: "飞天螳螂",
            french: "Insécateur",
        },
        type: ["Bug", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/123.png",
    },
    {
        id: 124,
        name: {
            english: "Jynx",
            japanese: "ルージュラ",
            chinese: "迷唇姐",
            french: "Lippoutou",
        },
        type: ["Ice", "Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/124.png",
    },
    {
        id: 125,
        name: {
            english: "Electabuzz",
            japanese: "エレブー",
            chinese: "电击兽",
            french: "Élektek",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/125.png",
    },
    {
        id: 126,
        name: {
            english: "Magmar",
            japanese: "ブーバー",
            chinese: "鸭嘴火兽",
            french: "Magmar",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/126.png",
    },
    {
        id: 127,
        name: {
            english: "Pinsir",
            japanese: "カイロス",
            chinese: "凯罗斯",
            french: "Scarabrute",
        },
        type: ["Bug"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/127.png",
    },
    {
        id: 128,
        name: {
            english: "Tauros",
            japanese: "ケンタロス",
            chinese: "肯泰罗",
            french: "Tauros",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/128.png",
    },
    {
        id: 129,
        name: {
            english: "Magikarp",
            japanese: "コイキング",
            chinese: "鲤鱼王",
            french: "Magicarpe",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/129.png",
    },
    {
        id: 130,
        name: {
            english: "Gyarados",
            japanese: "ギャラドス",
            chinese: "暴鲤龙",
            french: "Léviator",
        },
        type: ["Water", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png",
    },
    {
        id: 131,
        name: {
            english: "Lapras",
            japanese: "ラプラス",
            chinese: "拉普拉斯",
            french: "Lokhlass",
        },
        type: ["Water", "Ice"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/131.png",
    },
    {
        id: 132,
        name: {
            english: "Ditto",
            japanese: "メタモン",
            chinese: "百变怪",
            french: "Métamorph",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/132.png",
    },
    {
        id: 133,
        name: {
            english: "Eevee",
            japanese: "イーブイ",
            chinese: "伊布",
            french: "Évoli",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/133.png",
    },
    {
        id: 134,
        name: {
            english: "Vaporeon",
            japanese: "シャワーズ",
            chinese: "水伊布",
            french: "Aquali",
        },
        type: ["Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png",
    },
    {
        id: 135,
        name: {
            english: "Jolteon",
            japanese: "サンダース",
            chinese: "雷伊布",
            french: "Voltali",
        },
        type: ["Electric"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/135.png",
    },
    {
        id: 136,
        name: {
            english: "Flareon",
            japanese: "ブースター",
            chinese: "火伊布",
            french: "Pyroli",
        },
        type: ["Fire"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/136.png",
    },
    {
        id: 137,
        name: {
            english: "Porygon",
            japanese: "ポリゴン",
            chinese: "多边兽",
            french: "Porygon",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/137.png",
    },
    {
        id: 138,
        name: {
            english: "Omanyte",
            japanese: "オムナイト",
            chinese: "菊石兽",
            french: "Amonita",
        },
        type: ["Rock", "Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/138.png",
    },
    {
        id: 139,
        name: {
            english: "Omastar",
            japanese: "オムスター",
            chinese: "多刺菊石兽",
            french: "Amonistar",
        },
        type: ["Rock", "Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/139.png",
    },
    {
        id: 140,
        name: {
            english: "Kabuto",
            japanese: "カブト",
            chinese: "化石盔",
            french: "Kabuto",
        },
        type: ["Rock", "Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/140.png",
    },
    {
        id: 141,
        name: {
            english: "Kabutops",
            japanese: "カブトプス",
            chinese: "镰刀盔",
            french: "Kabutops",
        },
        type: ["Rock", "Water"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/141.png",
    },
    {
        id: 142,
        name: {
            english: "Aerodactyl",
            japanese: "プテラ",
            chinese: "化石翼龙",
            french: "Ptéra",
        },
        type: ["Rock", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/142.png",
    },
    {
        id: 143,
        name: {
            english: "Snorlax",
            japanese: "カビゴン",
            chinese: "卡比兽",
            french: "Ronflex",
        },
        type: ["Normal"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/143.png",
    },
    {
        id: 144,
        name: {
            english: "Articuno",
            japanese: "フリーザー",
            chinese: "急冻鸟",
            french: "Artikodin",
        },
        type: ["Ice", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/144.png",
    },
    {
        id: 145,
        name: {
            english: "Zapdos",
            japanese: "サンダー",
            chinese: "闪电鸟",
            french: "Électhor",
        },
        type: ["Electric", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/145.png",
    },
    {
        id: 146,
        name: {
            english: "Moltres",
            japanese: "ファイヤー",
            chinese: "火焰鸟",
            french: "Sulfura",
        },
        type: ["Fire", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/146.png",
    },
    {
        id: 147,
        name: {
            english: "Dratini",
            japanese: "ミニリュウ",
            chinese: "迷你龙",
            french: "Minidraco",
        },
        type: ["Dragon"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/147.png",
    },
    {
        id: 148,
        name: {
            english: "Dragonair",
            japanese: "ハクリュー",
            chinese: "哈克龙",
            french: "Draco",
        },
        type: ["Dragon"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/148.png",
    },
    {
        id: 149,
        name: {
            english: "Dragonite",
            japanese: "カイリュー",
            chinese: "快龙",
            french: "Dracolosse",
        },
        type: ["Dragon", "Flying"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png",
    },
    {
        id: 150,
        name: {
            english: "Mewtwo",
            japanese: "ミュウツー",
            chinese: "超梦",
            french: "Mewtwo",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png",
    },
    {
        id: 151,
        name: {
            english: "Mew",
            japanese: "ミュウ",
            chinese: "梦幻",
            french: "Mew",
        },
        type: ["Psychic"],
        image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/151.png",
    },
];
